### ISSUE TITLE
New version is broken - fail to deploy with the playbook example

### ISSUE THREAD

**Issue by danielporto** [Comcast/ansible-sdkman#21]
I tried to re-run the installation playbook given as an example (and pasted below) and it failed.
When I downgrade it to version 1.3.0 it runs without problems.
Running the playbook on mac to deploy on Centos7.

```
- hosts: clients_cluster, leader, replicas
  become: no
  any_errors_fatal: true
  vars_files:
      - play-vars.yml

  roles:
    - role: Comcast.sdkman
      sdkman_dir: "{{ sdkman_folder }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: "{{ java_version }}" }
        - { candidate: ant, version: "{{ ant_version }}" }
      sdkman_flush_caches_before:
        - temp
      sdkman_flush_caches_after:
        - archives
        - broadcast
        - candidates
        - temp
  ```
EDIT: @samrocketman added code blocks to ansible example.
