### ISSUE TITLE
The role comcast.sdkman is not idempotent

### ISSUE THREAD

**Issue by ollehallin** [Comcast/ansible-sdkman#48]
I have the following playbook:
```
---
- hosts: localhost
  connection: local
  vars:
  - sdkman_install_packages:
    - { candidate: java, version: '11.0.4-zulu' }
    - { candidate: java, version: '8.0.222-zulu' }
  - sdkman_defaults:
      java: '8.0.222-zulu'
  roles:
  - {role: comcast.sdkman, tags: sdkman}
```

Running the playbook twice fails the second time with the following play recap:
```
PLAY RECAP *****************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0
```

Expected play recap:
```
PLAY RECAP *****************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0
```

**comcast.sdkman version: 1.6.1**
