### ISSUE TITLE
Unable to execute privileged commands in role

### ISSUE THREAD

**Issue by artis3n** [Comcast/ansible-sdkman#60]
I am using `become: true` on my `import_role` task to call this role and setting `sdkman_user` and `sdkman_group` to the user who should be able to invoke sdkman.

However, I am hitting this error. `ansible_become_password` is set correctly and I can invoke other privileged commands without issue.

![2021-07-26_14-52-49](https://user-images.githubusercontent.com/6969296/127042969-a12a10f5-0817-44e2-8b7b-9acb70cbf4df.png)

What do I need to do to get the role working? I am on an OSX machine but the role executes without an issue on my OSX thing in CircleCI where the user is passwordless sudo. So I don't believe there is an OS incompatibility.

**Comment by elliotweiser** [comment]
@artis3n Hi! Please copy the exact way in which you are invoking this role, including the version of the role you have installed. Thanks!

**Comment by artis3n** [comment]
Yeah, absolutely. 

```
[WARNING]: - Comcast.sdkman (1.7.0) is already installed - use --force to
change version to unspecified
```

So 1.7.0 invoked in a playbook with:

```yml
- name: Java | Install SDKMan
  become: true
  ansible.builtin.import_role:
    name: Comcast.sdkman
  vars:
    sdkman_user: "{{ lookup('env', 'USER') }}"
    sdkman_group: staff
    sdkman_auto_answer: true
    sdkman_update: true
    sdkman_auto_selfupdate: true
    # This was moved to a vars.yml variable but Ansible threw interpolation errors so back it goes
    sdkman_install_packages:
      - {candidate: 'java', version: '16.0.1.hs-adpt'}
      - {candidate: 'java', version: '8.0.292.hs-adpt'}
      - {candidate: 'java', version: '11.0.12.7.2-amzn'}
    sdkman_defaults:
      java: '8.0.292.hs-adpt'
    sdkman_flush_caches_before:
      - temp
    sdkman_flush_caches_after:
      - archives
      - broadcast
      - candidates
      - temp
    sdkman_offline_mode: false
    sdkman_update_alternatives:
      - candidate: java
        name: java
        link: /usr/bin/java
      - candidate: java
        name: javac
        link: /usr/bin/javac
```
