### ISSUE TITLE
Interest in Arch/Manjaro support?

### ISSUE THREAD

**Issue by EugenMayer** [Comcast/ansible-sdkman#68]
We are using this playbook (for quiet a while now) for configuring our sdkman under manjaro.

I have seen that you officially support centos/debian/alpine but not arch. Would you be interested in getting this up and running?
I assume arch might be a choice especially for users which are developers, and i assume that is the exact audience for sdkman and thus for this playbook, or may i be mistaken?

Case is, it is currently broken with an very odd issue, `install.yml:20` fails with the exact error message `This is a bug`.

I tried to have an empty array for system_packages, but this seem to not have helped. Checking the playbook i have seen you having tests, but arch is not included. So i asked myself if we could get this up and running? 

In any way, thank you for the playbook!

**Comment by EugenMayer** [comment]
for the issue itself, it seems like calling the package manager of arch with nothing causes this issue - and since for a non matching / supported os the default of `system_packages` is an array, this causes the issue under arch.

One could use this for arch

```yaml
- name: init system_packages for Comcast.Sdkman for ardch
  set_facts:
    system_packages:
      - which
      - zip
      - unzip
      - findutils
      - curl
      - ca-certificates
      - openssl
```

For manjaro/arch i assume one needs to install this via AUR too:

```
- aur: name=libstdc++5-bin
```

We do this before triggering the playbook.

Other than this, it works fairly well (since 2 or 3 years). So you could probably make this compatible to arch fairly quick, if you like too.

For tests i would assume using `https://hub.docker.com/_/archlinux/` - i used this for my kitchen based tests too - you are using `molecule`, sure should not be a big difference.
